In [2]:

from pathlib import Path
import pandas as pd
import numpy as np
import json
import matplotlib.pyplot as plt

# Locate the directory containing the generated CSV files.
current_dir = Path.cwd()

possible_dirs = [
    current_dir / "cococare_stage1_outputs",
    current_dir.parent / "cococare_stage1_outputs",
    current_dir / "data" / "coconut_health",
]

output_dir = next(
    (
        p for p in possible_dirs
        if (p / "stage1_hybrid_dataset.csv").exists()
    ),
    None
)

if output_dir is None:
    raise FileNotFoundError(
        "Could not locate cococare_stage1_outputs. "
        f"Current working directory: {current_dir}. "
        "Update output_dir to the correct folder."
    )

print("Project output directory:", output_dir.resolve())

# Load the main generated dataset
dataset_path = output_dir / "stage1_hybrid_dataset.csv"
df_eval = pd.read_csv(dataset_path)

print("Dataset shape:", df_eval.shape)
print("Columns:", df_eval.columns.tolist())
display(df_eval.head())

Project output directory: /home/sivabharathi/Documents/FinalYearProject/CocoCare/ml/data/coconut_health/CocoCare_Stage1_Hybrid_Notebook/cococare_stage1_outputs
Dataset shape: (365, 30)
Columns: ['date', 'rainfall_mm', 'tmax_c', 'tmin_c', 'solar_radiation_mj_m2_day', 'relative_humidity_pct', 'wind_speed_m_s', 'weather_source', 'weather_source_url', 'et0_mm_day', 'etc_potential_mm_day_modelled', 'scenario', 'effective_rainfall_mm_modelled', 'runoff_mm_modelled', 'irrigation_mm_simulated', 'actual_et_mm_day_modelled', 'drainage_mm_modelled', 'soil_water_storage_mm_modelled', 'depletion_fraction_modelled', 'soil_moisture_vwc_pct_simulated', 'water_stress_rule_derived', 'recommended_action_simulated', 'model_status', 'location', 'latitude', 'longitude', 'variety', 'palm_age_months', 'data_class', 'stress_label_status']

,date,rainfall_mm,tmax_c,tmin_c,solar_radiation_mj_m2_day,relative_humidity_pct,wind_speed_m_s,weather_source,weather_source_url,et0_mm_day,...,water_stress_rule_derived,recommended_action_simulated,model_status,location,latitude,longitude,variety,palm_age_months,data_class,stress_label_status
0,2023-01-01,0.0,27.36,15.54,21.15,77.68,1.09,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.606898,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
1,2023-01-02,0.0,26.75,15.95,20.19,78.70,1.39,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.497985,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
2,2023-01-03,0.0,26.59,14.57,19.71,80.45,1.36,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.338542,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
3,2023-01-04,0.0,27.06,16.80,17.92,79.20,1.33,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.258480,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
4,2023-01-05,0.0,27.01,16.55,18.40,78.43,1.41,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.335836,...,high,consider_irrigation_if_field_conditions_confirm,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth

In [3]:

weather_path = output_dir / "coimbatore_nasa_power_weather.csv"
rules_path = output_dir / "tnau_reference_rules.csv"
metadata_path = output_dir / "stage1_metadata.json"

weather_df = pd.read_csv(weather_path)
tnau_df = pd.read_csv(rules_path)

with open(metadata_path, "r", encoding="utf-8") as f:
    metadata = json.load(f)

print("WEATHER DATA")
print(weather_df.shape)
display(weather_df.head())

print("\nTNAU REFERENCE RULES")
display(tnau_df)

print("\nMETADATA")
print(json.dumps(metadata, indent=2))

WEATHER DATA
(365, 9)

,date,rainfall_mm,tmax_c,tmin_c,solar_radiation_mj_m2_day,relative_humidity_pct,wind_speed_m_s,weather_source,weather_source_url
0,2023-01-01,0.0,27.36,15.54,21.15,77.68,1.09,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...
1,2023-01-02,0.0,26.75,15.95,20.19,78.70,1.39,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...
2,2023-01-03,0.0,26.59,14.57,19.71,80.45,1.36,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...
3,2023-01-04,0.0,27.06,16.80,17.92,79.20,1.33,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...
4,2023-01-05,0.0,27.01,16.55,18.40,78.43,1.41,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...

TNAU REFERENCE RULES

,topic,age_category,recommendation_summary,numeric_value,unit,conditions,source_url,source_type,status
0,young_palm_irrigation,first two years after planting,TNAU page states 45 L/seedling once every 4 da...,45,L/seedling/application,dry summer months; verify local applicability ...,https://www.agritech.tnau.ac.in/expert_system/...,official_extension_guidance,source_summary_to_verify_before_use
1,second_year_compost,second year after planting,TNAU table lists compost recommendation for se...,20,kg/palm/year,verify exact table and management context on o...,https://agritech.tnau.ac.in/expert_system/coco...,official_extension_guidance,source_summary_to_verify_before_use

METADATA
{
  "project": "CocoCare",
  "stage": "Stage 1",
  "variety": "East Coast Tall",
  "palm_age_months": 18,
  "location": "Pollachi, Tamil Nadu, India",
  "coordinates": {
    "latitude": 10.746,
    "longitude": 77.0976,
    "elevation_m_approx": 286.0
  },
  "weather_source": "NASA POWER daily point API",
  "weather_source_url": "https://power.larc.nasa.gov/docs/services/api/temporal/daily/",
  "weather_period": {
    "start": "2023-01-01",
    "end": "2023-12-31"
  },
  "agronomic_sources": {
    "TNAU irrigation": "https://www.agritech.tnau.ac.in/expert_system/coconut/coconut/coconut_irrigation_management.html",
    "TNAU nutrient management": "https://agritech.tnau.ac.in/expert_system/coconut/coconut/coconut_nutrient_management.html",
    "FAO-56 ET0": "https://www.fao.org/4/X0490E/x0490e0b.htm"
  },
  "formulas": {
    "ETc": "ETc = Kc * ET0 (FAO-56 crop coefficient approach)",
    "TAW": "TAW = (field_capacity_vwc - wilting_point_vwc) * root_zone_depth_m * 1000",
    "water_balance": "S_t = clip(S_(t-1) + effective_rainfall + irrigation - actual_ET - runoff - drainage, 0, TAW)"
  },
  "provisional_parameters": {
    "root_zone_depth_m": 0.45,
    "field_capacity_vwc_m3_m3": 0.23,
    "wilting_point_vwc_m3_m3": 0.1,
    "initial_available_water_fraction": 0.7,
    "runoff_fraction_of_rainfall": 0.05,
    "drainage_fraction_above_capacity": 0.5,
    "kc_provisional": 0.7,
    "depletion_trigger_fraction": 0.5
  },
  "limitations": [
    "NASA POWER is gridded weather data, not an on-farm sensor observation.",
    "Soil and crop parameters are provisional and require evidence or calibration.",
    "Modelled moisture and stress labels are not ground truth.",
    "The notebook's stress labels are derived from the same water-balance model being tested.",
    "No agronomic accuracy claim is justified without independent field validation."
  ]
}

In [4]:

# CocoCare: Weather data quality evaluation

import pandas as pd
import numpy as np
from IPython.display import display

# Parse dates
weather_df["date"] = pd.to_datetime(
    weather_df["date"], errors="coerce"
)

# 1. Basic checks
print("DATASET SHAPE:", weather_df.shape)
print("DATE RANGE:", weather_df["date"].min(),
      "to", weather_df["date"].max())
print("DUPLICATE ROWS:", weather_df.duplicated().sum())
print("DUPLICATE DATES:", weather_df["date"].duplicated().sum())

# 2. Missing values
missing = pd.DataFrame({
    "missing_count": weather_df.isna().sum(),
    "missing_percent": (
        weather_df.isna().mean() * 100
    ).round(2)
})
print("\nMISSING VALUE REPORT")
display(missing)

# 3. Check calendar coverage
expected_dates = pd.date_range(
    "2023-01-01", "2023-12-31", freq="D"
)
observed_dates = pd.DatetimeIndex(
    weather_df["date"].dropna().dt.normalize().unique()
)

missing_dates = expected_dates.difference(observed_dates)
print("\nEXPECTED DAYS:", len(expected_dates))
print("UNIQUE OBSERVED DAYS:", len(observed_dates))
print("MISSING CALENDAR DAYS:", len(missing_dates))
print("FIRST MISSING DATES:", missing_dates[:10].tolist())

# 4. Physical-range screening
ranges = {
    "rainfall_mm": (0, 500),
    "tmax_c": (-10, 60),
    "tmin_c": (-15, 50),
    "solar_radiation_mj_m2_day": (0, 45),
    "relative_humidity_pct": (0, 100),
    "wind_speed_m_s": (0, 75)
}

print("\nRANGE CHECKS")
for col, (low, high) in ranges.items():
    values = pd.to_numeric(weather_df[col], errors="coerce")
    count = ((values < low) | (values > high)).sum()
    print(f"{col}: {count} values outside screening range")

# 5. Temperature consistency
bad_temp = weather_df["tmax_c"] < weather_df["tmin_c"]
print("\nDAYS WHERE TMAX < TMIN:", int(bad_temp.sum()))

# 6. Numeric summary
print("\nNUMERIC SUMMARY")
display(
    weather_df[list(ranges)].describe().T.round(3)
)

DATASET SHAPE: (365, 9)
DATE RANGE: 2023-01-01 00:00:00 to 2023-12-31 00:00:00
DUPLICATE ROWS: 0
DUPLICATE DATES: 0

MISSING VALUE REPORT

                           missing_count  missing_percent
date                                   0              0.0
rainfall_mm                            0              0.0
tmax_c                                 0              0.0
tmin_c                                 0              0.0
solar_radiation_mj_m2_day              0              0.0
relative_humidity_pct                  0              0.0
wind_speed_m_s                         0              0.0
weather_source                         0              0.0
weather_source_url                     0              0.0

EXPECTED DAYS: 365
UNIQUE OBSERVED DAYS: 365
MISSING CALENDAR DAYS: 0
FIRST MISSING DATES: []

RANGE CHECKS
rainfall_mm: 0 values outside screening range
tmax_c: 0 values outside screening range
tmin_c: 0 values outside screening range
solar_radiation_mj_m2_day: 0 values outside screening range
relative_humidity_pct: 0 values outside screening range
wind_speed_m_s: 0 values outside screening range

DAYS WHERE TMAX < TMIN: 0

NUMERIC SUMMARY

,count,mean,std,min,25%,50%,75%,max
rainfall_mm,365.0,4.335,6.459,0.00,0.07,1.57,5.83,39.61
tmax_c,365.0,29.669,3.013,23.21,27.58,28.85,31.45,38.47
tmin_c,365.0,20.444,2.316,13.69,19.70,21.11,21.84,23.96
solar_radiation_mj_m2_day,365.0,19.220,4.163,6.61,16.08,19.73,22.42,27.31
relative_humidity_pct,365.0,78.470,12.481,40.37,72.54,83.60,87.29,93.93
wind_speed_m_s,365.0,1.452,0.568,0.38,1.07,1.42,1.83,3.29

In [5]:

hybrid_path = output_dir / "stage1_hybrid_dataset.csv"
hybrid_df = pd.read_csv(hybrid_path)

print("HYBRID DATASET SHAPE:", hybrid_df.shape)
print("\nCOLUMN NAMES:")
print(hybrid_df.columns.tolist())

print("\nFIRST FIVE ROWS:")
display(hybrid_df.head())

print("\nMISSING VALUES:")
display(
    pd.DataFrame({
        "missing_count": hybrid_df.isna().sum(),
        "missing_percent": (
            hybrid_df.isna().mean() * 100
        ).round(2)
    })
)

HYBRID DATASET SHAPE: (365, 30)

COLUMN NAMES:
['date', 'rainfall_mm', 'tmax_c', 'tmin_c', 'solar_radiation_mj_m2_day', 'relative_humidity_pct', 'wind_speed_m_s', 'weather_source', 'weather_source_url', 'et0_mm_day', 'etc_potential_mm_day_modelled', 'scenario', 'effective_rainfall_mm_modelled', 'runoff_mm_modelled', 'irrigation_mm_simulated', 'actual_et_mm_day_modelled', 'drainage_mm_modelled', 'soil_water_storage_mm_modelled', 'depletion_fraction_modelled', 'soil_moisture_vwc_pct_simulated', 'water_stress_rule_derived', 'recommended_action_simulated', 'model_status', 'location', 'latitude', 'longitude', 'variety', 'palm_age_months', 'data_class', 'stress_label_status']

FIRST FIVE ROWS:

,date,rainfall_mm,tmax_c,tmin_c,solar_radiation_mj_m2_day,relative_humidity_pct,wind_speed_m_s,weather_source,weather_source_url,et0_mm_day,...,water_stress_rule_derived,recommended_action_simulated,model_status,location,latitude,longitude,variety,palm_age_months,data_class,stress_label_status
0,2023-01-01,0.0,27.36,15.54,21.15,77.68,1.09,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.606898,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
1,2023-01-02,0.0,26.75,15.95,20.19,78.70,1.39,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.497985,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
2,2023-01-03,0.0,26.59,14.57,19.71,80.45,1.36,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.338542,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
3,2023-01-04,0.0,27.06,16.80,17.92,79.20,1.33,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.258480,...,moderate,recheck_soil_and_weather,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth
4,2023-01-05,0.0,27.01,16.55,18.40,78.43,1.41,NASA_POWER_daily_point,https://power.larc.nasa.gov/docs/services/api/...,3.335836,...,high,consider_irrigation_if_field_conditions_confirm,computed_using_provisional_parameters,"Pollachi, Tamil Nadu, India",10.746,77.0976,East Coast Tall,18,NASA_POWER_weather_plus_modelled_outputs,rule_derived_not_ground_truth

MISSING VALUES:

                                 missing_count  missing_percent
date                                         0              0.0
rainfall_mm                                  0              0.0
tmax_c                                       0              0.0
tmin_c                                       0              0.0
solar_radiation_mj_m2_day                    0              0.0
relative_humidity_pct                        0              0.0
wind_speed_m_s                               0              0.0
weather_source                               0              0.0
weather_source_url                           0              0.0
et0_mm_day                                   0              0.0
etc_potential_mm_day_modelled                0              0.0
scenario                                     0              0.0
effective_rainfall_mm_modelled               0              0.0
runoff_mm_modelled                           0              0.0
irrigation_mm_simulated                      0              0.0
actual_et_mm_day_modelled                    0              0.0
drainage_mm_modelled                         0              0.0
soil_water_storage_mm_modelled               0              0.0
depletion_fraction_modelled                  0              0.0
soil_moisture_vwc_pct_simulated              0              0.0
water_stress_rule_derived                    0              0.0
recommended_action_simulated                 0              0.0
model_status                                 0              0.0
location                                     0              0.0
latitude                                     0              0.0
longitude                                    0              0.0
variety                                      0              0.0
palm_age_months                              0              0.0
data_class                                   0              0.0
stress_label_status                          0              0.0

In [6]:

# CocoCare Stage 1: Distribution checks

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# hybrid_df was loaded in your previous cell
df_eval = hybrid_df.copy()
df_eval["date"] = pd.to_datetime(df_eval["date"], errors="coerce")

print("Rows:", len(df_eval))
print("Columns:", len(df_eval.columns))
print("Unique dates:", df_eval["date"].nunique())
print("Duplicate dates:", df_eval["date"].duplicated().sum())
print("Date range:", df_eval["date"].min(), "to", df_eval["date"].max())

print("\nScenario distribution:")
display(df_eval["scenario"].value_counts(dropna=False).to_frame("count"))

print("\nWater stress label distribution:")
display(
    df_eval["water_stress_rule_derived"]
    .value_counts(dropna=False)
    .to_frame("count")
)

print("\nRecommended action distribution:")
display(
    df_eval["recommended_action_simulated"]
    .value_counts(dropna=False)
    .to_frame("count")
)

numeric_cols = [
    "et0_mm_day",
    "etc_potential_mm_day_modelled",
    "effective_rainfall_mm_modelled",
    "runoff_mm_modelled",
    "irrigation_mm_simulated",
    "actual_et_mm_day_modelled",
    "drainage_mm_modelled",
    "soil_water_storage_mm_modelled",
    "depletion_fraction_modelled",
    "soil_moisture_vwc_pct_simulated",
]

display(df_eval[numeric_cols].describe().T.round(3))

Rows: 365
Columns: 30
Unique dates: 365
Duplicate dates: 0
Date range: 2023-01-01 00:00:00 to 2023-12-31 00:00:00

Scenario distribution:

              count
scenario
weather_only    365

Water stress label distribution:

                           count
water_stress_rule_derived
low                          197
high                         125
moderate                      43

Recommended action distribution:

                                                 count
recommended_action_simulated
continue_monitoring                                197
consider_irrigation_if_field_conditions_confirm    125
recheck_soil_and_weather                            43

,count,mean,std,min,25%,50%,75%,max
et0_mm_day,365.0,3.925,0.981,1.502,3.128,3.873,4.575,6.353
etc_potential_mm_day_modelled,365.0,2.748,0.687,1.051,2.190,2.711,3.203,4.447
effective_rainfall_mm_modelled,365.0,4.118,6.136,0.000,0.066,1.492,5.538,37.630
runoff_mm_modelled,365.0,0.217,0.323,0.000,0.004,0.078,0.292,1.980
irrigation_mm_simulated,365.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000
actual_et_mm_day_modelled,365.0,2.030,0.912,0.061,1.546,2.148,2.702,3.696
drainage_mm_modelled,365.0,1.045,2.642,0.000,0.000,0.000,0.172,18.070
soil_water_storage_mm_modelled,365.0,38.087,21.355,0.473,16.128,46.768,58.500,58.500
depletion_fraction_modelled,365.0,0.349,0.365,0.000,0.000,0.201,0.724,0.992
soil_moisture_vwc_pct_simulated,365.0,18.464,4.746,10.105,13.584,20.393,23.000,23.000

In [7]:

# CocoCare Stage 1: Basic physical-consistency checks

checks = []

def add_check(name, count, explanation):
    checks.append({
        "check": name,
        "flagged_rows": int(count),
        "interpretation": explanation
    })

# Non-negative quantities
nonnegative_cols = [
    "rainfall_mm",
    "solar_radiation_mj_m2_day",
    "wind_speed_m_s",
    "et0_mm_day",
    "etc_potential_mm_day_modelled",
    "effective_rainfall_mm_modelled",
    "runoff_mm_modelled",
    "irrigation_mm_simulated",
    "actual_et_mm_day_modelled",
    "drainage_mm_modelled",
    "soil_water_storage_mm_modelled",
]

for col in nonnegative_cols:
    values = pd.to_numeric(df_eval[col], errors="coerce")
    add_check(
        f"{col}: negative values",
        (values < -1e-8).sum(),
        "Investigate negative values; do not silently clip them."
    )

# Temperature consistency
add_check(
    "Maximum temperature below minimum",
    (df_eval["tmax_c"] < df_eval["tmin_c"]).sum(),
    "Maximum temperature should not be below minimum temperature."
)

# Relative humidity bounds
rh = df_eval["relative_humidity_pct"]
add_check(
    "Relative humidity outside 0–100%",
    ((rh < 0) | (rh > 100)).sum(),
    "Check source units and missing-value handling."
)

# Depletion fraction is normally bounded by the model's definition.
depletion = df_eval["depletion_fraction_modelled"]
add_check(
    "Depletion fraction outside 0–1",
    ((depletion < -1e-6) | (depletion > 1 + 1e-6)).sum(),
    "Check the depletion formula and clipping rules."
)

# Simulated volumetric water content percentage
vwc = df_eval["soil_moisture_vwc_pct_simulated"]
add_check(
    "Simulated VWC outside 0–100%",
    ((vwc < 0) | (vwc > 100)).sum(),
    "Check the conversion from storage to volumetric water content."
)

consistency_report = pd.DataFrame(checks)
display(consistency_report)

,check,flagged_rows,interpretation
0,rainfall_mm: negative values,0,Investigate negative values; do not silently c...
1,solar_radiation_mj_m2_day: negative values,0,Investigate negative values; do not silently c...
2,wind_speed_m_s: negative values,0,Investigate negative values; do not silently c...
3,et0_mm_day: negative values,0,Investigate negative values; do not silently c...
4,etc_potential_mm_day_modelled: negative values,0,Investigate negative values; do not silently c...
5,effective_rainfall_mm_modelled: negative values,0,Investigate negative values; do not silently c...
6,runoff_mm_modelled: negative values,0,Investigate negative values; do not silently c...
7,irrigation_mm_simulated: negative values,0,Investigate negative values; do not silently c...
8,actual_et_mm_day_modelled: negative values,0,Investigate negative values; do not silently c...
9,drainage_mm_modelled: negative values,0,Investigate negative values; do not silently c...
10,soil_water_storage_mm_modelled: negative values,0,Investigate negative values; do not silently c...
11,Maximum temperature below minimum,0,Maximum temperature should not be below minimu...
12,Relative humidity outside 0–100%,0,Check source units and missing-value handling.
13,Depletion fraction outside 0–1,0,Check the depletion formula and clipping rules.
14,Simulated VWC outside 0–100%,0,Check the conversion from storage to volumetri...

In [8]:

# CocoCare: daily water-balance consistency check

storage_col = "soil_water_storage_mm_modelled"

# The current configuration appears to use 58.5 mm as the
# maximum available storage. Confirm this against metadata/code.
TAW_ASSUMED = 58.5

balance = df_eval.sort_values("date").copy()

previous_storage = balance[storage_col].shift(1)

balance["storage_before_clipping_mm"] = (
    previous_storage
    + balance["effective_rainfall_mm_modelled"]
    + balance["irrigation_mm_simulated"]
    - balance["actual_et_mm_day_modelled"]
    - balance["runoff_mm_modelled"]
    - balance["drainage_mm_modelled"]
)

balance["storage_predicted_mm"] = (
    balance["storage_before_clipping_mm"]
    .clip(lower=0, upper=TAW_ASSUMED)
)

balance["storage_error_mm"] = (
    balance[storage_col] - balance["storage_predicted_mm"]
)

# First row is excluded because its previous day's storage
# is not available in this dataset.
checked = balance.iloc[1:].copy()

print("Days checked:", len(checked))
print(
    "Mean absolute storage error (mm):",
    checked["storage_error_mm"].abs().mean()
)
print(
    "Maximum absolute storage error (mm):",
    checked["storage_error_mm"].abs().max()
)
print(
    "Days with error > 0.01 mm:",
    (checked["storage_error_mm"].abs() > 0.01).sum()
)

display(
    checked.loc[
        checked["storage_error_mm"].abs() > 0.01,
        [
            "date",
            "soil_water_storage_mm_modelled",
            "storage_predicted_mm",
            "storage_error_mm"
        ]
    ].head(20)
)

Days checked: 364
Mean absolute storage error (mm): 0.07093525503147088
Maximum absolute storage error (mm): 0.9205000000000041
Days with error > 0.01 mm: 166

,date,soil_water_storage_mm_modelled,storage_predicted_mm,storage_error_mm
22,2023-01-23,7.431008,7.348508,0.0825
23,2023-01-24,13.801572,13.445072,0.3565
29,2023-01-30,8.703938,8.669438,0.0345
30,2023-01-31,8.426665,8.403165,0.0235
32,2023-02-02,10.046756,9.898256,0.1485
33,2023-02-03,13.227372,13.032372,0.1950
34,2023-02-04,14.703008,14.573508,0.1295
63,2023-03-05,3.205761,3.058761,0.1470
73,2023-03-15,1.363092,1.331592,0.0315
74,2023-03-16,2.283468,2.227968,0.0555
75,2023-03-17,13.614411,13.005911,0.6085
76,2023-03-18,15.370433,15.206433,0.1640
77,2023-03-19,16.088644,15.967144,0.1215
78,2023-03-20,16.474980,16.355980,0.1190
79,2023-03-21,14.910184,14.884184,0.0260
81,2023-03-23,11.900572,11.882572,0.0180
82,2023-03-24,12.945972,12.824972,0.1210
83,2023-03-25,15.421698,15.223198,0.1985
84,2023-03-26,18.312208,18.078708,0.2335
85,2023-03-27,17.555921,17.494921,0.0610

In [9]:

# Check the implied Kc from the stored ET0 and ETc values

valid_et0 = df_eval["et0_mm_day"] > 1e-8

implied_kc = (
    df_eval.loc[valid_et0, "etc_potential_mm_day_modelled"]
    / df_eval.loc[valid_et0, "et0_mm_day"]
)

print(implied_kc.describe())

print(
    "\nMedian implied Kc:",
    round(implied_kc.median(), 4)
)

count    3.650000e+02
mean     7.000000e-01
std      1.360985e-16
min      7.000000e-01
25%      7.000000e-01
50%      7.000000e-01
75%      7.000000e-01
max      7.000000e-01
dtype: float64

Median implied Kc: 0.7

In [10]:

# CocoCare: investigate the largest water-balance discrepancies

cols = [
    "date",
    "rainfall_mm",
    "effective_rainfall_mm_modelled",
    "runoff_mm_modelled",
    "irrigation_mm_simulated",
    "etc_potential_mm_day_modelled",
    "actual_et_mm_day_modelled",
    "drainage_mm_modelled",
    "soil_water_storage_mm_modelled",
    "storage_predicted_mm",
    "storage_error_mm",
]

diagnostic = balance[cols].copy()

# Exclude the first day because previous-day storage is unknown
diagnostic = diagnostic.iloc[1:].copy()

diagnostic["abs_error_mm"] = diagnostic["storage_error_mm"].abs()

display(
    diagnostic.sort_values(
        "abs_error_mm", ascending=False
    ).head(20)
)

,date,rainfall_mm,effective_rainfall_mm_modelled,runoff_mm_modelled,irrigation_mm_simulated,etc_potential_mm_day_modelled,actual_et_mm_day_modelled,drainage_mm_modelled,soil_water_storage_mm_modelled,storage_predicted_mm,storage_error_mm,abs_error_mm
243,2023-09-01,18.41,17.4895,0.9205,0.0,2.958622,2.958622,0.0,57.450583,56.530083,0.9205,0.9205
115,2023-04-26,17.90,17.0050,0.8950,0.0,2.921175,1.339387,0.0,29.077025,28.182025,0.8950,0.8950
116,2023-04-27,15.73,14.9435,0.7865,0.0,3.118360,3.099919,0.0,40.920606,40.134106,0.7865,0.7865
240,2023-08-29,14.15,13.4425,0.7075,0.0,2.842177,2.130498,0.0,33.237822,32.530322,0.7075,0.7075
219,2023-08-08,14.00,13.3000,0.7000,0.0,2.760037,2.760037,0.0,40.392332,39.692332,0.7000,0.7000
75,2023-03-17,12.17,11.5615,0.6085,0.0,2.953303,0.230556,0.0,13.614411,13.005911,0.6085,0.6085
167,2023-06-17,12.12,11.5140,0.6060,0.0,2.472223,2.472223,0.0,43.821721,43.215721,0.6060,0.6060
162,2023-06-12,11.53,10.9535,0.5765,0.0,2.875894,2.875894,0.0,39.033746,38.457246,0.5765,0.5765
280,2023-10-08,11.50,10.9250,0.5750,0.0,2.531425,2.531425,0.0,54.940366,54.365366,0.5750,0.5750
168,2023-06-18,10.55,10.0225,0.5275,0.0,2.022276,2.022276,0.0,51.821945,51.294445,0.5275,0.5275
241,2023-08-30,10.17,9.6615,0.5085,0.0,2.706166,2.706166,0.0,40.193157,39.684657,0.5085,0.5085
223,2023-08-12,10.13,9.6235,0.5065,0.0,2.621069,2.621069,0.0,55.416466,54.909966,0.5065,0.5065
117,2023-04-28,9.82,9.3290,0.4910,0.0,3.481411,3.481411,0.0,46.768195,46.277195,0.4910,0.4910
157,2023-06-07,9.73,9.2435,0.4865,0.0,3.250659,3.032203,0.0,33.495588,33.009088,0.4865,0.4865
114,2023-04-25,7.30,6.9350,0.3650,0.0,2.737461,0.668700,0.0,13.411413,13.046413,0.3650,0.3650
23,2023-01-24,7.13,6.7735,0.3565,0.0,1.586040,0.402936,0.0,13.801572,13.445072,0.3565,0.3565
222,2023-08-11,6.73,6.3935,0.3365,0.0,2.670211,2.670211,0.0,48.414035,48.077535,0.3365,0.3365
175,2023-06-25,6.58,6.2510,0.3290,0.0,2.544190,2.544190,0.0,57.211018,56.882018,0.3290,0.3290
317,2023-11-14,6.15,5.8425,0.3075,0.0,1.412416,1.412416,0.0,58.222483,57.914983,0.3075,0.3075
340,2023-12-07,6.10,5.7950,0.3050,0.0,2.092879,2.092879,0.0,57.088301,56.783301,0.3050,0.3050

In [11]:

# Diagnostic only: test whether runoff is already excluded
# from effective rainfall. Do not change the generator yet.

balance["storage_predicted_no_double_runoff_mm"] = (
    previous_storage
    + balance["effective_rainfall_mm_modelled"]
    + balance["irrigation_mm_simulated"]
    - balance["actual_et_mm_day_modelled"]
    - balance["drainage_mm_modelled"]
).clip(lower=0, upper=TAW_ASSUMED)

balance["error_no_double_runoff_mm"] = (
    balance["soil_water_storage_mm_modelled"]
    - balance["storage_predicted_no_double_runoff_mm"]
)

diagnostic_rows = balance.iloc[1:]

print(
    "Mean absolute error without second runoff subtraction:",
    diagnostic_rows["error_no_double_runoff_mm"].abs().mean()
)

print(
    "Maximum absolute error without second runoff subtraction:",
    diagnostic_rows["error_no_double_runoff_mm"].abs().max()
)

print(
    "Days with error > 0.01 mm:",
    (
        diagnostic_rows["error_no_double_runoff_mm"].abs() > 0.01
    ).sum()
)

display(
    diagnostic_rows[
        [
            "date",
            "rainfall_mm",
            "effective_rainfall_mm_modelled",
            "runoff_mm_modelled",
            "soil_water_storage_mm_modelled",
            "storage_predicted_no_double_runoff_mm",
            "error_no_double_runoff_mm"
        ]
    ].iloc[:10]
)

Mean absolute error without second runoff subtraction: 7.954564967643979e-16
Maximum absolute error without second runoff subtraction: 1.4210854715202004e-14
Days with error > 0.01 mm: 0

,date,rainfall_mm,effective_rainfall_mm_modelled,runoff_mm_modelled,soil_water_storage_mm_modelled,storage_predicted_no_double_runoff_mm,error_no_double_runoff_mm
1,2023-01-02,0.0,0.0,0.0,35.976582,35.976582,0.000000e+00
2,2023-01-03,0.0,0.0,0.0,33.639603,33.639603,0.000000e+00
3,2023-01-04,0.0,0.0,0.0,31.358667,31.358667,0.000000e+00
4,2023-01-05,0.0,0.0,0.0,29.023581,29.023581,0.000000e+00
5,2023-01-06,0.0,0.0,0.0,26.934414,26.934414,0.000000e+00
6,2023-01-07,0.0,0.0,0.0,24.893329,24.893329,-3.552714e-15
7,2023-01-08,0.0,0.0,0.0,23.148296,23.148296,3.552714e-15
8,2023-01-09,0.0,0.0,0.0,21.477799,21.477799,0.000000e+00
9,2023-01-10,0.0,0.0,0.0,19.539428,19.539428,3.552714e-15
10,2023-01-11,0.0,0.0,0.0,17.753525,17.753525,-3.552714e-15

In [12]:

# Final water-balance arithmetic validation

balance = df_eval.sort_values("date").copy()

TAW_ASSUMED = 58.5  # Confirm against generator configuration

previous_storage = (
    balance["soil_water_storage_mm_modelled"].shift(1)
)

predicted_storage = (
    previous_storage
    + balance["effective_rainfall_mm_modelled"]
    + balance["irrigation_mm_simulated"]
    - balance["actual_et_mm_day_modelled"]
    - balance["drainage_mm_modelled"]
).clip(lower=0, upper=TAW_ASSUMED)

observed_storage = balance["soil_water_storage_mm_modelled"]

error = observed_storage - predicted_storage
valid_error = error.iloc[1:].dropna()

print("Days evaluated:", len(valid_error))
print("Mean absolute error (mm):", valid_error.abs().mean())
print("Maximum absolute error (mm):", valid_error.abs().max())
print("Days with error > 0.01 mm:",
      (valid_error.abs() > 0.01).sum())

assert valid_error.abs().max() < 1e-8, (
    "Water-balance mismatch: inspect generator logic."
)

print("\nPASS: Stored water balance matches the reconstructed equation.")

Days evaluated: 364
Mean absolute error (mm): 7.954564967643979e-16
Maximum absolute error (mm): 1.4210854715202004e-14
Days with error > 0.01 mm: 0

PASS: Stored water balance matches the reconstructed equation.